import { Game } from './../model/game';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class GameService {

  private games = new Array<Game>(); // AGORA O INJECTABLE SABE DE SUA EXISTENCIA
  private autoGeneratedId = 0; // AUTO GERADOR PARA INCREMENTAR ID

  constructor() { }

  // RECEBERÁ TODO O JOGO DE GAMES.TS
  insert(game: Game): void{
    game.id = this.autoGeneratedId;
    this.games.push(game); //PEGA O JOGO COMO PARAMETRO
    this.autoGeneratedId++; // INCREMENTA O ID
  }

  // RETORNA O ARRAY DE GAME
  list(): Array<Game>{
    return this.games;
  }

  remove(id: number): void{
    this.games = this.games.filter((game) =>{
      return game.id !== id;
    });
  }

  update(game: Game): void{
    const i = this.games.findIndex(g => g.id == game.id);
    if(i >= 0){
      this.games[i] = game;
    }
  }

}

// OUTROS EXEMPLOS
 /* remove(id: number): void{
    for(let i = 0; this.games.length; i++){
      const g = this.games[i]; // PEGA A POSIÇÃO DO ARRAY
      if(id === g.id){ // COMPARA ID COM O DO JOGO
        this.games.splice(i, 1); // REMOVE A PISIÇÃO (i), APENAS 1 (1)
        break;
      }
    }
  }*/

  /*remove(id: number): void{
    this.games.forEach((game, i) => {
      if(id === game.id){ // COMPARA ID COM O DO JOGO
        this.games.splice(i, 1); // REMOVE A PISIÇÃO (i), APENAS 1 (1)
      }
    });
  }*/
